[package]
name = "hopfieldnetwork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
itertools = "0.10.5"
nalgebra = "0.32.1"
rand = "0.8.5"
rand_distr = "0.4.3"
